# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_menu_page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 1075)
        MainWindow.setMaximumSize(QtCore.QSize(1147, 1500))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(34, 34, 46);\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(69, 69, 106);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(251, 91, 93);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(53, 53, 81);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(251, 91, 93);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(53, 53, 81);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(251, 91, 93);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"       border: none;\n"
"    background: rgb(45, 45, 68);\n"
"   \n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    background-color: rgb(80, 80, 122);\n"
"\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"\n"
"\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(34, 34, 46)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(34, 34, 46);\n"
" }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -5855, 1131, 7300))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 7300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(1090, 7000))
        self.frame.setMaximumSize(QtCore.QSize(1095, 300000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 130, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color :rgb(255, 255, 255);\n"
"background-color:rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 260, 961, 131))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(100, 390, 911, 301))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(560, 1440, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(180, 980, 251, 181))
        self.label_6.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("page1_images/p_O (1).jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(180, 1200, 251, 181))
        self.label_10.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("page1_images/u-cb6bcd96eed201d27bacfc0f6ff58d03.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(180, 1420, 251, 181))
        self.label_11.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("page1_images/Lentil_soup_01.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(200, 1830, 251, 181))
        self.label_13.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("page1_images/Pshennaya-kasha-s-tykvoy-na-moloke-Shag-6.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(200, 2070, 251, 181))
        self.label_17.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("page1_images/u-2aa8fbfe700ea40546ee5d8e8d311e29.jpg"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(200, 2300, 251, 181))
        self.label_20.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("page1_images/4fc475dcc8aada55269d2a7bd92401fb.jpg"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(120, 1720, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(200, 3150, 251, 181))
        self.label_22.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("page1_images/6279.jpg"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(200, 2920, 251, 181))
        self.label_25.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("page1_images/5-luchshikh-rietsieptov-irlandskogho-miasnogho-raghu-основное-фото-рецепта.jpg"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(200, 2690, 251, 181))
        self.label_26.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("page1_images/p_O.jpg"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(120, 2580, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(190, 4020, 251, 181))
        self.label_32.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("page1_images/zelyonji-borshch-so-shchavelem_1578545912_9_max.jpg"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(190, 3790, 251, 181))
        self.label_35.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("page1_images/svinina_po-kitaiski_s_ovoshami-88532.jpg"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(190, 3560, 251, 181))
        self.label_36.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("page1_images/p_O (2).jpg"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_40 = QtWidgets.QLabel(self.frame)
        self.label_40.setGeometry(QtCore.QRect(120, 3450, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_43 = QtWidgets.QLabel(self.frame)
        self.label_43.setGeometry(QtCore.QRect(180, 4900, 251, 181))
        self.label_43.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("page1_images/2611073_15270-330x220x.jpg"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame)
        self.label_44.setGeometry(QtCore.QRect(180, 4440, 251, 181))
        self.label_44.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("page1_images/Без названия.jpg"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.label_48 = QtWidgets.QLabel(self.frame)
        self.label_48.setGeometry(QtCore.QRect(180, 4670, 251, 181))
        self.label_48.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("page1_images/photo.jpg"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame)
        self.label_49.setGeometry(QtCore.QRect(120, 4320, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_53 = QtWidgets.QLabel(self.frame)
        self.label_53.setGeometry(QtCore.QRect(180, 5760, 251, 181))
        self.label_53.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("page1_images/140605181246.jpg"))
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.frame)
        self.label_54.setGeometry(QtCore.QRect(180, 5300, 251, 181))
        self.label_54.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_54.setText("")
        self.label_54.setPixmap(QtGui.QPixmap("page1_images/bdcaa404.jpg"))
        self.label_54.setScaledContents(True)
        self.label_54.setObjectName("label_54")
        self.label_58 = QtWidgets.QLabel(self.frame)
        self.label_58.setGeometry(QtCore.QRect(180, 5530, 251, 181))
        self.label_58.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap("page1_images/b4795b7d.jpg"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.frame)
        self.label_59.setGeometry(QtCore.QRect(120, 5190, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.label_63 = QtWidgets.QLabel(self.frame)
        self.label_63.setGeometry(QtCore.QRect(180, 6640, 251, 181))
        self.label_63.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_63.setText("")
        self.label_63.setPixmap(QtGui.QPixmap("page1_images/farshirovannii_perec_po-moldavski-603564.jpg"))
        self.label_63.setScaledContents(True)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.frame)
        self.label_64.setGeometry(QtCore.QRect(180, 6180, 251, 181))
        self.label_64.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_64.setText("")
        self.label_64.setPixmap(QtGui.QPixmap("page1_images/Без названия (1).jpg"))
        self.label_64.setScaledContents(True)
        self.label_64.setObjectName("label_64")
        self.label_68 = QtWidgets.QLabel(self.frame)
        self.label_68.setGeometry(QtCore.QRect(180, 6410, 251, 181))
        self.label_68.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap("page1_images/grecheskaya-musaka-s-baklazhanami-i-govyazhim-farshem.jpg"))
        self.label_68.setScaledContents(True)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.frame)
        self.label_69.setGeometry(QtCore.QRect(120, 6070, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.label_73 = QtWidgets.QLabel(self.frame)
        self.label_73.setGeometry(QtCore.QRect(310, 6980, 551, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_73.setObjectName("label_73")
        self.label_72 = QtWidgets.QLabel(self.frame)
        self.label_72.setGeometry(QtCore.QRect(120, 860, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 940, 921, 711))
        self.label_2.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(550, 1030, 401, 131))
        self.label_4.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(660, 1040, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_52 = QtWidgets.QLabel(self.frame)
        self.label_52.setGeometry(QtCore.QRect(810, 1090, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_52.setObjectName("label_52")
        self.mon_brf_g = QtWidgets.QLabel(self.frame)
        self.mon_brf_g.setGeometry(QtCore.QRect(640, 1090, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g.setFont(font)
        self.mon_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g.setObjectName("mon_brf_g")
        self.mon_brf_kal = QtWidgets.QLabel(self.frame)
        self.mon_brf_kal.setGeometry(QtCore.QRect(750, 1090, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_kal.setFont(font)
        self.mon_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_kal.setObjectName("mon_brf_kal")
        self.label_51 = QtWidgets.QLabel(self.frame)
        self.label_51.setGeometry(QtCore.QRect(700, 1090, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_51.setObjectName("label_51")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(550, 1250, 401, 131))
        self.label_16.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(650, 1260, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(620, 1480, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(560, 1470, 401, 131))
        self.label_18.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_47 = QtWidgets.QLabel(self.frame)
        self.label_47.setGeometry(QtCore.QRect(560, 1420, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(self.frame)
        self.label_50.setGeometry(QtCore.QRect(550, 1200, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_55 = QtWidgets.QLabel(self.frame)
        self.label_55.setGeometry(QtCore.QRect(550, 980, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame)
        self.label_56.setGeometry(QtCore.QRect(810, 1310, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_56.setObjectName("label_56")
        self.mon_lch_g = QtWidgets.QLabel(self.frame)
        self.mon_lch_g.setGeometry(QtCore.QRect(630, 1310, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_g.setFont(font)
        self.mon_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_g.setObjectName("mon_lch_g")
        self.mon_lch_kal = QtWidgets.QLabel(self.frame)
        self.mon_lch_kal.setGeometry(QtCore.QRect(740, 1310, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_kal.setFont(font)
        self.mon_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_kal.setObjectName("mon_lch_kal")
        self.label_60 = QtWidgets.QLabel(self.frame)
        self.label_60.setGeometry(QtCore.QRect(690, 1310, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_60.setObjectName("label_60")
        self.mon_dnr_g = QtWidgets.QLabel(self.frame)
        self.mon_dnr_g.setGeometry(QtCore.QRect(640, 1530, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_dnr_g.setFont(font)
        self.mon_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_dnr_g.setObjectName("mon_dnr_g")
        self.label_61 = QtWidgets.QLabel(self.frame)
        self.label_61.setGeometry(QtCore.QRect(810, 1530, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.frame)
        self.label_62.setGeometry(QtCore.QRect(700, 1530, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_62.setObjectName("label_62")
        self.mon_dnr_kal = QtWidgets.QLabel(self.frame)
        self.mon_dnr_kal.setGeometry(QtCore.QRect(750, 1530, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_dnr_kal.setFont(font)
        self.mon_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_dnr_kal.setObjectName("mon_dnr_kal")
        self.label_65 = QtWidgets.QLabel(self.frame)
        self.label_65.setGeometry(QtCore.QRect(560, 2280, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.frame)
        self.label_66.setGeometry(QtCore.QRect(550, 1840, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.frame)
        self.label_67.setGeometry(QtCore.QRect(550, 2060, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(550, 2110, 401, 131))
        self.label_19.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_70 = QtWidgets.QLabel(self.frame)
        self.label_70.setGeometry(QtCore.QRect(560, 2330, 401, 131))
        self.label_70.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_70.setText("")
        self.label_70.setObjectName("label_70")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(550, 1890, 401, 131))
        self.label_12.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 1800, 921, 711))
        self.label_3.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_57 = QtWidgets.QLabel(self.frame)
        self.label_57.setGeometry(QtCore.QRect(560, 3150, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.label_71 = QtWidgets.QLabel(self.frame)
        self.label_71.setGeometry(QtCore.QRect(550, 2690, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.label_74 = QtWidgets.QLabel(self.frame)
        self.label_74.setGeometry(QtCore.QRect(550, 2920, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(550, 2970, 401, 131))
        self.label_23.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(560, 3200, 401, 131))
        self.label_24.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(550, 2740, 401, 131))
        self.label_14.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(120, 2660, 921, 711))
        self.label_15.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(550, 3840, 401, 131))
        self.label_27.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_75 = QtWidgets.QLabel(self.frame)
        self.label_75.setGeometry(QtCore.QRect(550, 3560, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(550, 4070, 401, 131))
        self.label_28.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(550, 3610, 401, 131))
        self.label_29.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_76 = QtWidgets.QLabel(self.frame)
        self.label_76.setGeometry(QtCore.QRect(550, 3790, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.frame)
        self.label_77.setGeometry(QtCore.QRect(550, 4020, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(120, 3530, 921, 711))
        self.label_31.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_78 = QtWidgets.QLabel(self.frame)
        self.label_78.setGeometry(QtCore.QRect(550, 4900, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(550, 4490, 401, 131))
        self.label_33.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_79 = QtWidgets.QLabel(self.frame)
        self.label_79.setGeometry(QtCore.QRect(550, 4440, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.frame)
        self.label_80.setGeometry(QtCore.QRect(550, 4670, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(120, 4410, 921, 711))
        self.label_34.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(550, 4720, 401, 131))
        self.label_37.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_81 = QtWidgets.QLabel(self.frame)
        self.label_81.setGeometry(QtCore.QRect(550, 4950, 401, 131))
        self.label_81.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_81.setText("")
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.frame)
        self.label_82.setGeometry(QtCore.QRect(550, 5760, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.label_38 = QtWidgets.QLabel(self.frame)
        self.label_38.setGeometry(QtCore.QRect(550, 5350, 401, 131))
        self.label_38.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_83 = QtWidgets.QLabel(self.frame)
        self.label_83.setGeometry(QtCore.QRect(550, 5300, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.frame)
        self.label_84.setGeometry(QtCore.QRect(550, 5530, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.label_39 = QtWidgets.QLabel(self.frame)
        self.label_39.setGeometry(QtCore.QRect(120, 5270, 921, 711))
        self.label_39.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_41 = QtWidgets.QLabel(self.frame)
        self.label_41.setGeometry(QtCore.QRect(550, 5580, 401, 131))
        self.label_41.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_85 = QtWidgets.QLabel(self.frame)
        self.label_85.setGeometry(QtCore.QRect(550, 5810, 401, 131))
        self.label_85.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_85.setText("")
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.frame)
        self.label_86.setGeometry(QtCore.QRect(550, 6640, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.label_42 = QtWidgets.QLabel(self.frame)
        self.label_42.setGeometry(QtCore.QRect(550, 6230, 401, 131))
        self.label_42.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_87 = QtWidgets.QLabel(self.frame)
        self.label_87.setGeometry(QtCore.QRect(550, 6180, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_87.setFont(font)
        self.label_87.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.frame)
        self.label_88.setGeometry(QtCore.QRect(550, 6410, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.label_45 = QtWidgets.QLabel(self.frame)
        self.label_45.setGeometry(QtCore.QRect(120, 6150, 921, 711))
        self.label_45.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame)
        self.label_46.setGeometry(QtCore.QRect(550, 6460, 401, 131))
        self.label_46.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.label_89 = QtWidgets.QLabel(self.frame)
        self.label_89.setGeometry(QtCore.QRect(550, 6690, 401, 131))
        self.label_89.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_89.setText("")
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.frame)
        self.label_90.setGeometry(QtCore.QRect(810, 1950, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_90.setFont(font)
        self.label_90.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.frame)
        self.label_91.setGeometry(QtCore.QRect(600, 1900, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_91.setObjectName("label_91")
        self.tue_brf_g = QtWidgets.QLabel(self.frame)
        self.tue_brf_g.setGeometry(QtCore.QRect(640, 1950, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tue_brf_g.setFont(font)
        self.tue_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.tue_brf_g.setObjectName("tue_brf_g")
        self.tue_brf_kal = QtWidgets.QLabel(self.frame)
        self.tue_brf_kal.setGeometry(QtCore.QRect(750, 1950, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tue_brf_kal.setFont(font)
        self.tue_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.tue_brf_kal.setObjectName("tue_brf_kal")
        self.label_92 = QtWidgets.QLabel(self.frame)
        self.label_92.setGeometry(QtCore.QRect(700, 1950, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_92.setObjectName("label_92")
        self.tue_lch_kal = QtWidgets.QLabel(self.frame)
        self.tue_lch_kal.setGeometry(QtCore.QRect(740, 2170, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tue_lch_kal.setFont(font)
        self.tue_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.tue_lch_kal.setObjectName("tue_lch_kal")
        self.tue_lch_g = QtWidgets.QLabel(self.frame)
        self.tue_lch_g.setGeometry(QtCore.QRect(630, 2170, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tue_lch_g.setFont(font)
        self.tue_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.tue_lch_g.setObjectName("tue_lch_g")
        self.label_93 = QtWidgets.QLabel(self.frame)
        self.label_93.setGeometry(QtCore.QRect(810, 2170, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.frame)
        self.label_94.setGeometry(QtCore.QRect(660, 2120, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_94.setFont(font)
        self.label_94.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.frame)
        self.label_95.setGeometry(QtCore.QRect(690, 2170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_95.setFont(font)
        self.label_95.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_95.setObjectName("label_95")
        self.tue_dnr_kal = QtWidgets.QLabel(self.frame)
        self.tue_dnr_kal.setGeometry(QtCore.QRect(750, 2390, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tue_dnr_kal.setFont(font)
        self.tue_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.tue_dnr_kal.setObjectName("tue_dnr_kal")
        self.tue_dnr_g = QtWidgets.QLabel(self.frame)
        self.tue_dnr_g.setGeometry(QtCore.QRect(640, 2390, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tue_dnr_g.setFont(font)
        self.tue_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.tue_dnr_g.setObjectName("tue_dnr_g")
        self.label_96 = QtWidgets.QLabel(self.frame)
        self.label_96.setGeometry(QtCore.QRect(810, 2390, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_96.setFont(font)
        self.label_96.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.frame)
        self.label_97.setGeometry(QtCore.QRect(660, 2340, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_97.setFont(font)
        self.label_97.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.frame)
        self.label_98.setGeometry(QtCore.QRect(700, 2390, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_98.setFont(font)
        self.label_98.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_98.setObjectName("label_98")
        self.wed_brf_kal = QtWidgets.QLabel(self.frame)
        self.wed_brf_kal.setGeometry(QtCore.QRect(750, 2800, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wed_brf_kal.setFont(font)
        self.wed_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.wed_brf_kal.setObjectName("wed_brf_kal")
        self.wed_brf_g = QtWidgets.QLabel(self.frame)
        self.wed_brf_g.setGeometry(QtCore.QRect(640, 2800, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wed_brf_g.setFont(font)
        self.wed_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.wed_brf_g.setObjectName("wed_brf_g")
        self.label_99 = QtWidgets.QLabel(self.frame)
        self.label_99.setGeometry(QtCore.QRect(810, 2800, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_99.setFont(font)
        self.label_99.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.frame)
        self.label_100.setGeometry(QtCore.QRect(660, 2750, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_100.setFont(font)
        self.label_100.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.frame)
        self.label_101.setGeometry(QtCore.QRect(700, 2800, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_101.setFont(font)
        self.label_101.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_101.setObjectName("label_101")
        self.wed_lch_kal = QtWidgets.QLabel(self.frame)
        self.wed_lch_kal.setGeometry(QtCore.QRect(750, 3030, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wed_lch_kal.setFont(font)
        self.wed_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.wed_lch_kal.setObjectName("wed_lch_kal")
        self.wed_lch_g = QtWidgets.QLabel(self.frame)
        self.wed_lch_g.setGeometry(QtCore.QRect(640, 3030, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wed_lch_g.setFont(font)
        self.wed_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.wed_lch_g.setObjectName("wed_lch_g")
        self.label_102 = QtWidgets.QLabel(self.frame)
        self.label_102.setGeometry(QtCore.QRect(820, 3030, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_102.setFont(font)
        self.label_102.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.frame)
        self.label_103.setGeometry(QtCore.QRect(640, 2980, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_103.setFont(font)
        self.label_103.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.frame)
        self.label_104.setGeometry(QtCore.QRect(700, 3030, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_104.setFont(font)
        self.label_104.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_104.setObjectName("label_104")
        self.wed_dnr_kal = QtWidgets.QLabel(self.frame)
        self.wed_dnr_kal.setGeometry(QtCore.QRect(760, 3270, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wed_dnr_kal.setFont(font)
        self.wed_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.wed_dnr_kal.setObjectName("wed_dnr_kal")
        self.wed_dnr_g = QtWidgets.QLabel(self.frame)
        self.wed_dnr_g.setGeometry(QtCore.QRect(650, 3270, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wed_dnr_g.setFont(font)
        self.wed_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.wed_dnr_g.setObjectName("wed_dnr_g")
        self.label_105 = QtWidgets.QLabel(self.frame)
        self.label_105.setGeometry(QtCore.QRect(820, 3270, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_105.setFont(font)
        self.label_105.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_105.setObjectName("label_105")
        self.label_106 = QtWidgets.QLabel(self.frame)
        self.label_106.setGeometry(QtCore.QRect(610, 3220, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_106.setFont(font)
        self.label_106.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_106.setObjectName("label_106")
        self.label_107 = QtWidgets.QLabel(self.frame)
        self.label_107.setGeometry(QtCore.QRect(710, 3270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_107.setFont(font)
        self.label_107.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_107.setObjectName("label_107")
        self.label_108 = QtWidgets.QLabel(self.frame)
        self.label_108.setGeometry(QtCore.QRect(810, 3670, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_108.setFont(font)
        self.label_108.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_108.setObjectName("label_108")
        self.label_109 = QtWidgets.QLabel(self.frame)
        self.label_109.setGeometry(QtCore.QRect(700, 3670, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_109.setFont(font)
        self.label_109.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_109.setObjectName("label_109")
        self.thu_brf_g = QtWidgets.QLabel(self.frame)
        self.thu_brf_g.setGeometry(QtCore.QRect(640, 3670, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.thu_brf_g.setFont(font)
        self.thu_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.thu_brf_g.setObjectName("thu_brf_g")
        self.label_110 = QtWidgets.QLabel(self.frame)
        self.label_110.setGeometry(QtCore.QRect(600, 3620, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_110.setFont(font)
        self.label_110.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_110.setObjectName("label_110")
        self.thu_brf_kal = QtWidgets.QLabel(self.frame)
        self.thu_brf_kal.setGeometry(QtCore.QRect(750, 3670, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.thu_brf_kal.setFont(font)
        self.thu_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.thu_brf_kal.setObjectName("thu_brf_kal")
        self.label_111 = QtWidgets.QLabel(self.frame)
        self.label_111.setGeometry(QtCore.QRect(820, 3900, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_111.setFont(font)
        self.label_111.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_111.setObjectName("label_111")
        self.label_112 = QtWidgets.QLabel(self.frame)
        self.label_112.setGeometry(QtCore.QRect(700, 3900, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_112.setFont(font)
        self.label_112.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_112.setObjectName("label_112")
        self.thu_lch_g = QtWidgets.QLabel(self.frame)
        self.thu_lch_g.setGeometry(QtCore.QRect(640, 3900, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.thu_lch_g.setFont(font)
        self.thu_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.thu_lch_g.setObjectName("thu_lch_g")
        self.label_113 = QtWidgets.QLabel(self.frame)
        self.label_113.setGeometry(QtCore.QRect(620, 3850, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_113.setFont(font)
        self.label_113.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_113.setObjectName("label_113")
        self.thu_lch_kal = QtWidgets.QLabel(self.frame)
        self.thu_lch_kal.setGeometry(QtCore.QRect(750, 3900, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.thu_lch_kal.setFont(font)
        self.thu_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.thu_lch_kal.setObjectName("thu_lch_kal")
        self.label_114 = QtWidgets.QLabel(self.frame)
        self.label_114.setGeometry(QtCore.QRect(810, 4140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_114.setFont(font)
        self.label_114.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.frame)
        self.label_115.setGeometry(QtCore.QRect(700, 4140, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_115.setFont(font)
        self.label_115.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_115.setObjectName("label_115")
        self.thu_dnr_g = QtWidgets.QLabel(self.frame)
        self.thu_dnr_g.setGeometry(QtCore.QRect(640, 4140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.thu_dnr_g.setFont(font)
        self.thu_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.thu_dnr_g.setObjectName("thu_dnr_g")
        self.label_116 = QtWidgets.QLabel(self.frame)
        self.label_116.setGeometry(QtCore.QRect(650, 4090, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_116.setFont(font)
        self.label_116.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_116.setObjectName("label_116")
        self.thu_dnr_kal = QtWidgets.QLabel(self.frame)
        self.thu_dnr_kal.setGeometry(QtCore.QRect(750, 4140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.thu_dnr_kal.setFont(font)
        self.thu_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.thu_dnr_kal.setObjectName("thu_dnr_kal")
        self.label_117 = QtWidgets.QLabel(self.frame)
        self.label_117.setGeometry(QtCore.QRect(810, 4560, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_117.setFont(font)
        self.label_117.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(self.frame)
        self.label_118.setGeometry(QtCore.QRect(700, 4560, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_118.setFont(font)
        self.label_118.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_118.setObjectName("label_118")
        self.fri_brf_g = QtWidgets.QLabel(self.frame)
        self.fri_brf_g.setGeometry(QtCore.QRect(640, 4560, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fri_brf_g.setFont(font)
        self.fri_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.fri_brf_g.setObjectName("fri_brf_g")
        self.label_119 = QtWidgets.QLabel(self.frame)
        self.label_119.setGeometry(QtCore.QRect(630, 4510, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_119.setFont(font)
        self.label_119.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_119.setObjectName("label_119")
        self.fri_brf_kal = QtWidgets.QLabel(self.frame)
        self.fri_brf_kal.setGeometry(QtCore.QRect(750, 4560, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fri_brf_kal.setFont(font)
        self.fri_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.fri_brf_kal.setObjectName("fri_brf_kal")
        self.label_120 = QtWidgets.QLabel(self.frame)
        self.label_120.setGeometry(QtCore.QRect(660, 4740, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_120.setFont(font)
        self.label_120.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_120.setObjectName("label_120")
        self.fri_lch_g = QtWidgets.QLabel(self.frame)
        self.fri_lch_g.setGeometry(QtCore.QRect(640, 4790, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fri_lch_g.setFont(font)
        self.fri_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.fri_lch_g.setObjectName("fri_lch_g")
        self.label_121 = QtWidgets.QLabel(self.frame)
        self.label_121.setGeometry(QtCore.QRect(700, 4790, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_121.setFont(font)
        self.label_121.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_121.setObjectName("label_121")
        self.fri_lch_kal = QtWidgets.QLabel(self.frame)
        self.fri_lch_kal.setGeometry(QtCore.QRect(750, 4790, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fri_lch_kal.setFont(font)
        self.fri_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.fri_lch_kal.setObjectName("fri_lch_kal")
        self.label_122 = QtWidgets.QLabel(self.frame)
        self.label_122.setGeometry(QtCore.QRect(820, 4790, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_122.setFont(font)
        self.label_122.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_122.setObjectName("label_122")
        self.label_123 = QtWidgets.QLabel(self.frame)
        self.label_123.setGeometry(QtCore.QRect(660, 4970, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_123.setFont(font)
        self.label_123.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_123.setObjectName("label_123")
        self.fri_dnr_g = QtWidgets.QLabel(self.frame)
        self.fri_dnr_g.setGeometry(QtCore.QRect(640, 5020, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fri_dnr_g.setFont(font)
        self.fri_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.fri_dnr_g.setObjectName("fri_dnr_g")
        self.label_124 = QtWidgets.QLabel(self.frame)
        self.label_124.setGeometry(QtCore.QRect(700, 5020, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_124.setFont(font)
        self.label_124.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_124.setObjectName("label_124")
        self.fri_dnr_kal = QtWidgets.QLabel(self.frame)
        self.fri_dnr_kal.setGeometry(QtCore.QRect(750, 5020, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fri_dnr_kal.setFont(font)
        self.fri_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.fri_dnr_kal.setObjectName("fri_dnr_kal")
        self.label_125 = QtWidgets.QLabel(self.frame)
        self.label_125.setGeometry(QtCore.QRect(810, 5020, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_125.setFont(font)
        self.label_125.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_125.setObjectName("label_125")
        self.label_126 = QtWidgets.QLabel(self.frame)
        self.label_126.setGeometry(QtCore.QRect(680, 5370, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_126.setFont(font)
        self.label_126.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_126.setObjectName("label_126")
        self.sat_brf_g = QtWidgets.QLabel(self.frame)
        self.sat_brf_g.setGeometry(QtCore.QRect(640, 5420, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sat_brf_g.setFont(font)
        self.sat_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sat_brf_g.setObjectName("sat_brf_g")
        self.label_127 = QtWidgets.QLabel(self.frame)
        self.label_127.setGeometry(QtCore.QRect(700, 5420, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_127.setFont(font)
        self.label_127.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_127.setObjectName("label_127")
        self.sat_brf_kal = QtWidgets.QLabel(self.frame)
        self.sat_brf_kal.setGeometry(QtCore.QRect(750, 5420, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sat_brf_kal.setFont(font)
        self.sat_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sat_brf_kal.setObjectName("sat_brf_kal")
        self.label_128 = QtWidgets.QLabel(self.frame)
        self.label_128.setGeometry(QtCore.QRect(810, 5420, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_128.setFont(font)
        self.label_128.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.frame)
        self.label_129.setGeometry(QtCore.QRect(650, 5600, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_129.setFont(font)
        self.label_129.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_129.setObjectName("label_129")
        self.sat_lch_g = QtWidgets.QLabel(self.frame)
        self.sat_lch_g.setGeometry(QtCore.QRect(640, 5650, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sat_lch_g.setFont(font)
        self.sat_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sat_lch_g.setObjectName("sat_lch_g")
        self.label_130 = QtWidgets.QLabel(self.frame)
        self.label_130.setGeometry(QtCore.QRect(700, 5650, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_130.setFont(font)
        self.label_130.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_130.setObjectName("label_130")
        self.sat_lch_kal = QtWidgets.QLabel(self.frame)
        self.sat_lch_kal.setGeometry(QtCore.QRect(750, 5650, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sat_lch_kal.setFont(font)
        self.sat_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sat_lch_kal.setObjectName("sat_lch_kal")
        self.label_131 = QtWidgets.QLabel(self.frame)
        self.label_131.setGeometry(QtCore.QRect(810, 5650, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_131.setFont(font)
        self.label_131.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_131.setObjectName("label_131")
        self.label_132 = QtWidgets.QLabel(self.frame)
        self.label_132.setGeometry(QtCore.QRect(640, 5830, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_132.setFont(font)
        self.label_132.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_132.setObjectName("label_132")
        self.sat_dnr_g = QtWidgets.QLabel(self.frame)
        self.sat_dnr_g.setGeometry(QtCore.QRect(640, 5880, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sat_dnr_g.setFont(font)
        self.sat_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sat_dnr_g.setObjectName("sat_dnr_g")
        self.label_133 = QtWidgets.QLabel(self.frame)
        self.label_133.setGeometry(QtCore.QRect(700, 5880, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_133.setFont(font)
        self.label_133.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_133.setObjectName("label_133")
        self.sat_dnr_kal = QtWidgets.QLabel(self.frame)
        self.sat_dnr_kal.setGeometry(QtCore.QRect(750, 5880, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sat_dnr_kal.setFont(font)
        self.sat_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sat_dnr_kal.setObjectName("sat_dnr_kal")
        self.label_134 = QtWidgets.QLabel(self.frame)
        self.label_134.setGeometry(QtCore.QRect(810, 5880, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_134.setFont(font)
        self.label_134.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_134.setObjectName("label_134")
        self.label_135 = QtWidgets.QLabel(self.frame)
        self.label_135.setGeometry(QtCore.QRect(660, 6250, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_135.setFont(font)
        self.label_135.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_135.setObjectName("label_135")
        self.sun_brf_g = QtWidgets.QLabel(self.frame)
        self.sun_brf_g.setGeometry(QtCore.QRect(640, 6300, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sun_brf_g.setFont(font)
        self.sun_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sun_brf_g.setObjectName("sun_brf_g")
        self.label_136 = QtWidgets.QLabel(self.frame)
        self.label_136.setGeometry(QtCore.QRect(700, 6300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_136.setFont(font)
        self.label_136.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_136.setObjectName("label_136")
        self.sun_brf_kal = QtWidgets.QLabel(self.frame)
        self.sun_brf_kal.setGeometry(QtCore.QRect(750, 6300, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sun_brf_kal.setFont(font)
        self.sun_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sun_brf_kal.setObjectName("sun_brf_kal")
        self.label_137 = QtWidgets.QLabel(self.frame)
        self.label_137.setGeometry(QtCore.QRect(810, 6300, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_137.setFont(font)
        self.label_137.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_137.setObjectName("label_137")
        self.label_138 = QtWidgets.QLabel(self.frame)
        self.label_138.setGeometry(QtCore.QRect(700, 6480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_138.setFont(font)
        self.label_138.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_138.setObjectName("label_138")
        self.sun_lch_g = QtWidgets.QLabel(self.frame)
        self.sun_lch_g.setGeometry(QtCore.QRect(640, 6530, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sun_lch_g.setFont(font)
        self.sun_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sun_lch_g.setObjectName("sun_lch_g")
        self.label_139 = QtWidgets.QLabel(self.frame)
        self.label_139.setGeometry(QtCore.QRect(700, 6530, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_139.setFont(font)
        self.label_139.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_139.setObjectName("label_139")
        self.sun_lch_kal = QtWidgets.QLabel(self.frame)
        self.sun_lch_kal.setGeometry(QtCore.QRect(750, 6530, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sun_lch_kal.setFont(font)
        self.sun_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sun_lch_kal.setObjectName("sun_lch_kal")
        self.label_140 = QtWidgets.QLabel(self.frame)
        self.label_140.setGeometry(QtCore.QRect(820, 6530, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_140.setFont(font)
        self.label_140.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_140.setObjectName("label_140")
        self.label_141 = QtWidgets.QLabel(self.frame)
        self.label_141.setGeometry(QtCore.QRect(600, 6710, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_141.setFont(font)
        self.label_141.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_141.setObjectName("label_141")
        self.sun_dnr_g = QtWidgets.QLabel(self.frame)
        self.sun_dnr_g.setGeometry(QtCore.QRect(640, 6760, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sun_dnr_g.setFont(font)
        self.sun_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sun_dnr_g.setObjectName("sun_dnr_g")
        self.label_142 = QtWidgets.QLabel(self.frame)
        self.label_142.setGeometry(QtCore.QRect(700, 6760, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_142.setFont(font)
        self.label_142.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_142.setObjectName("label_142")
        self.sun_dnr_kal = QtWidgets.QLabel(self.frame)
        self.sun_dnr_kal.setGeometry(QtCore.QRect(750, 6760, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sun_dnr_kal.setFont(font)
        self.sun_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.sun_dnr_kal.setObjectName("sun_dnr_kal")
        self.label_143 = QtWidgets.QLabel(self.frame)
        self.label_143.setGeometry(QtCore.QRect(810, 6760, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_143.setFont(font)
        self.label_143.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_143.setObjectName("label_143")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(80, 700, 961, 131))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_45.raise_()
        self.label_42.raise_()
        self.label_88.raise_()
        self.label_46.raise_()
        self.label_89.raise_()
        self.label_86.raise_()
        self.label_87.raise_()
        self.label_39.raise_()
        self.label_84.raise_()
        self.label_38.raise_()
        self.label_83.raise_()
        self.label_41.raise_()
        self.label_82.raise_()
        self.label_85.raise_()
        self.label_34.raise_()
        self.label_33.raise_()
        self.label_37.raise_()
        self.label_79.raise_()
        self.label_78.raise_()
        self.label_81.raise_()
        self.label_80.raise_()
        self.label_31.raise_()
        self.label_28.raise_()
        self.label_27.raise_()
        self.label_76.raise_()
        self.label_75.raise_()
        self.label_29.raise_()
        self.label_77.raise_()
        self.label_15.raise_()
        self.label_57.raise_()
        self.label_74.raise_()
        self.label_14.raise_()
        self.label_24.raise_()
        self.label_71.raise_()
        self.label_23.raise_()
        self.label.raise_()
        self.plainTextEdit.raise_()
        self.plainTextEdit_2.raise_()
        self.label_5.raise_()
        self.label_21.raise_()
        self.label_30.raise_()
        self.label_40.raise_()
        self.label_49.raise_()
        self.label_59.raise_()
        self.label_69.raise_()
        self.label_73.raise_()
        self.label_72.raise_()
        self.label_2.raise_()
        self.label_11.raise_()
        self.label_6.raise_()
        self.label_10.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_52.raise_()
        self.mon_brf_g.raise_()
        self.mon_brf_kal.raise_()
        self.label_51.raise_()
        self.label_16.raise_()
        self.label_8.raise_()
        self.label_18.raise_()
        self.label_9.raise_()
        self.label_47.raise_()
        self.label_50.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.mon_lch_g.raise_()
        self.mon_lch_kal.raise_()
        self.label_60.raise_()
        self.mon_dnr_g.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.mon_dnr_kal.raise_()
        self.label_3.raise_()
        self.label_66.raise_()
        self.label_12.raise_()
        self.label_65.raise_()
        self.label_67.raise_()
        self.label_19.raise_()
        self.label_70.raise_()
        self.label_20.raise_()
        self.label_17.raise_()
        self.label_13.raise_()
        self.label_22.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_32.raise_()
        self.label_48.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.label_54.raise_()
        self.label_58.raise_()
        self.label_53.raise_()
        self.label_64.raise_()
        self.label_63.raise_()
        self.label_68.raise_()
        self.label_90.raise_()
        self.label_91.raise_()
        self.tue_brf_g.raise_()
        self.tue_brf_kal.raise_()
        self.label_92.raise_()
        self.tue_lch_kal.raise_()
        self.tue_lch_g.raise_()
        self.label_93.raise_()
        self.label_94.raise_()
        self.label_95.raise_()
        self.tue_dnr_kal.raise_()
        self.tue_dnr_g.raise_()
        self.label_96.raise_()
        self.label_97.raise_()
        self.label_98.raise_()
        self.wed_brf_kal.raise_()
        self.wed_brf_g.raise_()
        self.label_99.raise_()
        self.label_100.raise_()
        self.label_101.raise_()
        self.wed_lch_kal.raise_()
        self.wed_lch_g.raise_()
        self.label_102.raise_()
        self.label_103.raise_()
        self.label_104.raise_()
        self.wed_dnr_kal.raise_()
        self.wed_dnr_g.raise_()
        self.label_105.raise_()
        self.label_106.raise_()
        self.label_107.raise_()
        self.label_108.raise_()
        self.label_109.raise_()
        self.thu_brf_g.raise_()
        self.label_110.raise_()
        self.thu_brf_kal.raise_()
        self.label_111.raise_()
        self.label_112.raise_()
        self.thu_lch_g.raise_()
        self.label_113.raise_()
        self.thu_lch_kal.raise_()
        self.label_114.raise_()
        self.label_115.raise_()
        self.thu_dnr_g.raise_()
        self.label_116.raise_()
        self.thu_dnr_kal.raise_()
        self.label_117.raise_()
        self.label_118.raise_()
        self.fri_brf_g.raise_()
        self.label_119.raise_()
        self.fri_brf_kal.raise_()
        self.label_120.raise_()
        self.fri_lch_g.raise_()
        self.label_121.raise_()
        self.fri_lch_kal.raise_()
        self.label_122.raise_()
        self.label_123.raise_()
        self.fri_dnr_g.raise_()
        self.label_124.raise_()
        self.fri_dnr_kal.raise_()
        self.label_125.raise_()
        self.label_126.raise_()
        self.sat_brf_g.raise_()
        self.label_127.raise_()
        self.sat_brf_kal.raise_()
        self.label_128.raise_()
        self.label_129.raise_()
        self.sat_lch_g.raise_()
        self.label_130.raise_()
        self.sat_lch_kal.raise_()
        self.label_131.raise_()
        self.label_132.raise_()
        self.sat_dnr_g.raise_()
        self.label_133.raise_()
        self.sat_dnr_kal.raise_()
        self.label_134.raise_()
        self.label_135.raise_()
        self.sun_brf_g.raise_()
        self.label_136.raise_()
        self.sun_brf_kal.raise_()
        self.label_137.raise_()
        self.label_138.raise_()
        self.sun_lch_g.raise_()
        self.label_139.raise_()
        self.sun_lch_kal.raise_()
        self.label_140.raise_()
        self.label_141.raise_()
        self.sun_dnr_g.raise_()
        self.label_142.raise_()
        self.sun_dnr_kal.raise_()
        self.label_143.raise_()
        self.plainTextEdit_3.raise_()
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Меню на неделю"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "В данной записи представлено разнообразное меню на неделю с готовым отчетом по потребляемым калориям и питательным веществам. Это меню было составлено исходя из следующих принципов:\n"
""))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "• На завтрак мы едим лёгкую и быстро готовящуюся пищу, например, кашу\n"
"• На обед приходится самый калорийный приём пищи\n"
"• На ужин мы готовим рецепт средней калорийности, например, суп\n"
"• По крайней мере один раз в день мы едим овощное блюдо или суп\n"
"• По крайней мере один раз в день – рыбное или мясное блюдо\n"
"• Средний дневной рацион потребления углеводов, жиров и белков должен удовлетворять рекомендованную норму (см. Википедию)\n"
"• Каждый день в меню входит белковая, углеводная и овощная пища\n"
"• Для того, чтобы разнообразить рацион питания, мы в один день не повторяем один и тот же гарнир (рис, картофель или макароны), и стараемся избегать повторения одних и тех же продуктов."))
        self.label_5.setText(_translate("MainWindow", "Ужин"))
        self.label_21.setText(_translate("MainWindow", "Вторник"))
        self.label_30.setText(_translate("MainWindow", "Среда"))
        self.label_40.setText(_translate("MainWindow", "Четверг"))
        self.label_49.setText(_translate("MainWindow", "Пятница"))
        self.label_59.setText(_translate("MainWindow", "Суббота"))
        self.label_69.setText(_translate("MainWindow", "Воскресенье"))
        self.label_73.setText(_translate("MainWindow", "Приятного аппетита!"))
        self.label_72.setText(_translate("MainWindow", "Понедельник"))
        self.label_7.setText(_translate("MainWindow", "Каша ячневая"))
        self.label_52.setText(_translate("MainWindow", "ккал"))
        self.mon_brf_g.setText(_translate("MainWindow", "402"))
        self.mon_brf_kal.setText(_translate("MainWindow", "491"))
        self.label_51.setText(_translate("MainWindow", "г  /"))
        self.label_8.setText(_translate("MainWindow", "Тефтели с рисом"))
        self.label_9.setText(_translate("MainWindow", "Суп-пюре из чечевицы"))
        self.label_47.setText(_translate("MainWindow", "Ужин"))
        self.label_50.setText(_translate("MainWindow", "Обед"))
        self.label_55.setText(_translate("MainWindow", "Завтрак"))
        self.label_56.setText(_translate("MainWindow", "ккал"))
        self.mon_lch_g.setText(_translate("MainWindow", "562"))
        self.mon_lch_kal.setText(_translate("MainWindow", "1258"))
        self.label_60.setText(_translate("MainWindow", "г  /"))
        self.mon_dnr_g.setText(_translate("MainWindow", "542"))
        self.label_61.setText(_translate("MainWindow", "ккал"))
        self.label_62.setText(_translate("MainWindow", "г  /"))
        self.mon_dnr_kal.setText(_translate("MainWindow", "401"))
        self.label_65.setText(_translate("MainWindow", "Ужин"))
        self.label_66.setText(_translate("MainWindow", "Завтрак"))
        self.label_67.setText(_translate("MainWindow", "Обед"))
        self.label_57.setText(_translate("MainWindow", "Ужин"))
        self.label_71.setText(_translate("MainWindow", "Завтрак"))
        self.label_74.setText(_translate("MainWindow", "Обед"))
        self.label_75.setText(_translate("MainWindow", "Завтрак"))
        self.label_76.setText(_translate("MainWindow", "Обед"))
        self.label_77.setText(_translate("MainWindow", "Ужин"))
        self.label_78.setText(_translate("MainWindow", "Ужин"))
        self.label_79.setText(_translate("MainWindow", "Завтрак"))
        self.label_80.setText(_translate("MainWindow", "Обед"))
        self.label_82.setText(_translate("MainWindow", "Ужин"))
        self.label_83.setText(_translate("MainWindow", "Завтрак"))
        self.label_84.setText(_translate("MainWindow", "Обед"))
        self.label_86.setText(_translate("MainWindow", "Ужин"))
        self.label_87.setText(_translate("MainWindow", "Завтрак"))
        self.label_88.setText(_translate("MainWindow", "Обед"))
        self.label_90.setText(_translate("MainWindow", "ккал"))
        self.label_91.setText(_translate("MainWindow", "Пшенная каша с тыквой"))
        self.tue_brf_g.setText(_translate("MainWindow", "490"))
        self.tue_brf_kal.setText(_translate("MainWindow", "270"))
        self.label_92.setText(_translate("MainWindow", "г  /"))
        self.tue_lch_kal.setText(_translate("MainWindow", "1163"))
        self.tue_lch_g.setText(_translate("MainWindow", "644"))
        self.label_93.setText(_translate("MainWindow", "ккал"))
        self.label_94.setText(_translate("MainWindow", "Карри с бобами нут"))
        self.label_95.setText(_translate("MainWindow", "г  /"))
        self.tue_dnr_kal.setText(_translate("MainWindow", "430"))
        self.tue_dnr_g.setText(_translate("MainWindow", "402"))
        self.label_96.setText(_translate("MainWindow", "ккал"))
        self.label_97.setText(_translate("MainWindow", "Куриный суп"))
        self.label_98.setText(_translate("MainWindow", "г  /"))
        self.wed_brf_kal.setText(_translate("MainWindow", "659"))
        self.wed_brf_g.setText(_translate("MainWindow", "522"))
        self.label_99.setText(_translate("MainWindow", "ккал"))
        self.label_100.setText(_translate("MainWindow", "Манная каша"))
        self.label_101.setText(_translate("MainWindow", "г  /"))
        self.wed_lch_kal.setText(_translate("MainWindow", "713"))
        self.wed_lch_g.setText(_translate("MainWindow", "665"))
        self.label_102.setText(_translate("MainWindow", "ккал"))
        self.label_103.setText(_translate("MainWindow", "Ирландское рагу"))
        self.label_104.setText(_translate("MainWindow", "г  /"))
        self.wed_dnr_kal.setText(_translate("MainWindow", "628"))
        self.wed_dnr_g.setText(_translate("MainWindow", "484"))
        self.label_105.setText(_translate("MainWindow", "ккал"))
        self.label_106.setText(_translate("MainWindow", "Жареная цветная капуста"))
        self.label_107.setText(_translate("MainWindow", "г  /"))
        self.label_108.setText(_translate("MainWindow", "ккал"))
        self.label_109.setText(_translate("MainWindow", "г  /"))
        self.thu_brf_g.setText(_translate("MainWindow", "464"))
        self.label_110.setText(_translate("MainWindow", "Жидкая пшенная каша"))
        self.thu_brf_kal.setText(_translate("MainWindow", "566"))
        self.label_111.setText(_translate("MainWindow", "ккал"))
        self.label_112.setText(_translate("MainWindow", "г  /"))
        self.thu_lch_g.setText(_translate("MainWindow", "590"))
        self.label_113.setText(_translate("MainWindow", "Свинина по-китайски"))
        self.thu_lch_kal.setText(_translate("MainWindow", "1051"))
        self.label_114.setText(_translate("MainWindow", "ккал"))
        self.label_115.setText(_translate("MainWindow", "г  /"))
        self.thu_dnr_g.setText(_translate("MainWindow", "556"))
        self.label_116.setText(_translate("MainWindow", "Зелёный борщ"))
        self.thu_dnr_kal.setText(_translate("MainWindow", "528"))
        self.label_117.setText(_translate("MainWindow", "ккал"))
        self.label_118.setText(_translate("MainWindow", "г  /"))
        self.fri_brf_g.setText(_translate("MainWindow", "434"))
        self.label_119.setText(_translate("MainWindow", "Овсянка на молоке"))
        self.fri_brf_kal.setText(_translate("MainWindow", "647"))
        self.label_120.setText(_translate("MainWindow", "Мясной рулет"))
        self.fri_lch_g.setText(_translate("MainWindow", "484"))
        self.label_121.setText(_translate("MainWindow", "г  /"))
        self.fri_lch_kal.setText(_translate("MainWindow", "950"))
        self.label_122.setText(_translate("MainWindow", "ккал"))
        self.label_123.setText(_translate("MainWindow", "Уха бурлацкая"))
        self.fri_dnr_g.setText(_translate("MainWindow", "658"))
        self.label_124.setText(_translate("MainWindow", "г  /"))
        self.fri_dnr_kal.setText(_translate("MainWindow", "402"))
        self.label_125.setText(_translate("MainWindow", "ккал"))
        self.label_126.setText(_translate("MainWindow", "Гречники"))
        self.sat_brf_g.setText(_translate("MainWindow", "438"))
        self.label_127.setText(_translate("MainWindow", "г  /"))
        self.sat_brf_kal.setText(_translate("MainWindow", "478"))
        self.label_128.setText(_translate("MainWindow", "ккал"))
        self.label_129.setText(_translate("MainWindow", "Паста с лососем"))
        self.sat_lch_g.setText(_translate("MainWindow", "458"))
        self.label_130.setText(_translate("MainWindow", "г  /"))
        self.sat_lch_kal.setText(_translate("MainWindow", "459"))
        self.label_131.setText(_translate("MainWindow", "ккал"))
        self.label_132.setText(_translate("MainWindow", "Солянка грибная"))
        self.sat_dnr_g.setText(_translate("MainWindow", "804"))
        self.label_133.setText(_translate("MainWindow", "г  /"))
        self.sat_dnr_kal.setText(_translate("MainWindow", "535"))
        self.label_134.setText(_translate("MainWindow", "ккал"))
        self.label_135.setText(_translate("MainWindow", "Каша рисовая"))
        self.sun_brf_g.setText(_translate("MainWindow", "418"))
        self.label_136.setText(_translate("MainWindow", "г  /"))
        self.sun_brf_kal.setText(_translate("MainWindow", "587"))
        self.label_137.setText(_translate("MainWindow", "ккал"))
        self.label_138.setText(_translate("MainWindow", "Мусака"))
        self.sun_lch_g.setText(_translate("MainWindow", "544"))
        self.label_139.setText(_translate("MainWindow", "г  /"))
        self.sun_lch_kal.setText(_translate("MainWindow", "956"))
        self.label_140.setText(_translate("MainWindow", "ккал"))
        self.label_141.setText(_translate("MainWindow", "Перцы фаршированные"))
        self.sun_dnr_g.setText(_translate("MainWindow", "514"))
        self.label_142.setText(_translate("MainWindow", "г  /"))
        self.sun_dnr_kal.setText(_translate("MainWindow", "635"))
        self.label_143.setText(_translate("MainWindow", "ккал"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "* При подсчете пищевой ценности подразумевается, что вы при каждом приеме пищи закусываете хлебом (2 ломтика)\n"
""))
