# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_menu_page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 1075)
        MainWindow.setMaximumSize(QtCore.QSize(1147, 1500))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(34, 34, 46);\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(69, 69, 106);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(251, 91, 93);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(53, 53, 81);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(251, 91, 93);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(53, 53, 81);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(251, 91, 93);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"       border: none;\n"
"    background: rgb(45, 45, 68);\n"
"   \n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    background-color: rgb(80, 80, 122);\n"
"\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"\n"
"\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(34, 34, 46)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(34, 34, 46);\n"
" }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -39, 1131, 2500))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 2500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(1090, 4000))
        self.frame.setMaximumSize(QtCore.QSize(1095, 300000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(260, 190, 641, 71))
        font = QtGui.QFont()
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color :rgb(255, 255, 255);\n"
"background-color:rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 330, 961, 131))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(100, 460, 911, 361))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(560, 1440, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(180, 980, 251, 181))
        self.label_6.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("page2_images/gerkulesovaya-kasha-na-vode-vkusno_1521794111_5_max.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(180, 1200, 251, 181))
        self.label_10.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("page2_images/scale_1200.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(180, 1420, 251, 181))
        self.label_11.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("page2_images/unnamed.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_72 = QtWidgets.QLabel(self.frame)
        self.label_72.setGeometry(QtCore.QRect(120, 860, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(251, 91, 93);\n"
"border-radius: 30;")
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 940, 921, 1371))
        self.label_2.setStyleSheet("background-color: rgb(52, 52, 71);\n"
"border-radius: 30;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(550, 1030, 401, 131))
        self.label_4.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(570, 1030, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_52 = QtWidgets.QLabel(self.frame)
        self.label_52.setGeometry(QtCore.QRect(810, 1100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_52.setObjectName("label_52")
        self.mon_brf_g = QtWidgets.QLabel(self.frame)
        self.mon_brf_g.setGeometry(QtCore.QRect(660, 1100, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g.setFont(font)
        self.mon_brf_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g.setObjectName("mon_brf_g")
        self.mon_brf_kal = QtWidgets.QLabel(self.frame)
        self.mon_brf_kal.setGeometry(QtCore.QRect(760, 1100, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_kal.setFont(font)
        self.mon_brf_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_kal.setObjectName("mon_brf_kal")
        self.label_51 = QtWidgets.QLabel(self.frame)
        self.label_51.setGeometry(QtCore.QRect(710, 1100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_51.setObjectName("label_51")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(550, 1250, 401, 131))
        self.label_16.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(550, 1470, 401, 131))
        self.label_18.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_47 = QtWidgets.QLabel(self.frame)
        self.label_47.setGeometry(QtCore.QRect(550, 1420, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(self.frame)
        self.label_50.setGeometry(QtCore.QRect(550, 1200, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_55 = QtWidgets.QLabel(self.frame)
        self.label_55.setGeometry(QtCore.QRect(550, 980, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_144 = QtWidgets.QLabel(self.frame)
        self.label_144.setGeometry(QtCore.QRect(570, 1060, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_144.setFont(font)
        self.label_144.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_144.setObjectName("label_144")
        self.mon_brf_g_2 = QtWidgets.QLabel(self.frame)
        self.mon_brf_g_2.setGeometry(QtCore.QRect(570, 1100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g_2.setFont(font)
        self.mon_brf_g_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g_2.setObjectName("mon_brf_g_2")
        self.label_73 = QtWidgets.QLabel(self.frame)
        self.label_73.setGeometry(QtCore.QRect(300, 2340, 551, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_73.setObjectName("label_73")
        self.label_57 = QtWidgets.QLabel(self.frame)
        self.label_57.setGeometry(QtCore.QRect(550, 1640, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(550, 1690, 401, 131))
        self.label_8.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_58 = QtWidgets.QLabel(self.frame)
        self.label_58.setGeometry(QtCore.QRect(550, 1860, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(550, 1910, 401, 131))
        self.label_9.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_59 = QtWidgets.QLabel(self.frame)
        self.label_59.setGeometry(QtCore.QRect(550, 2080, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("background-color: rgb(34, 34, 46);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20;")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(550, 2130, 401, 131))
        self.label_12.setStyleSheet("background-color: rgb(43, 43, 58);\n"
"border-radius: 30;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.mon_brf_g_4 = QtWidgets.QLabel(self.frame)
        self.mon_brf_g_4.setGeometry(QtCore.QRect(570, 1980, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g_4.setFont(font)
        self.mon_brf_g_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g_4.setObjectName("mon_brf_g_4")
        self.label_149 = QtWidgets.QLabel(self.frame)
        self.label_149.setGeometry(QtCore.QRect(570, 1940, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_149.setFont(font)
        self.label_149.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_149.setObjectName("label_149")
        self.label_61 = QtWidgets.QLabel(self.frame)
        self.label_61.setGeometry(QtCore.QRect(810, 1980, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_61.setObjectName("label_61")
        self.mon_dnr_kal = QtWidgets.QLabel(self.frame)
        self.mon_dnr_kal.setGeometry(QtCore.QRect(760, 1980, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_dnr_kal.setFont(font)
        self.mon_dnr_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_dnr_kal.setObjectName("mon_dnr_kal")
        self.label_150 = QtWidgets.QLabel(self.frame)
        self.label_150.setGeometry(QtCore.QRect(570, 1910, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_150.setFont(font)
        self.label_150.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_150.setObjectName("label_150")
        self.mon_dnr_g = QtWidgets.QLabel(self.frame)
        self.mon_dnr_g.setGeometry(QtCore.QRect(660, 1980, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_dnr_g.setFont(font)
        self.mon_dnr_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_dnr_g.setObjectName("mon_dnr_g")
        self.label_62 = QtWidgets.QLabel(self.frame)
        self.label_62.setGeometry(QtCore.QRect(710, 1980, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_62.setObjectName("label_62")
        self.mon_brf_g_3 = QtWidgets.QLabel(self.frame)
        self.mon_brf_g_3.setGeometry(QtCore.QRect(570, 1540, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g_3.setFont(font)
        self.mon_brf_g_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g_3.setObjectName("mon_brf_g_3")
        self.mon_lch_g = QtWidgets.QLabel(self.frame)
        self.mon_lch_g.setGeometry(QtCore.QRect(660, 1540, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_g.setFont(font)
        self.mon_lch_g.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_g.setObjectName("mon_lch_g")
        self.label_146 = QtWidgets.QLabel(self.frame)
        self.label_146.setGeometry(QtCore.QRect(570, 1500, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_146.setFont(font)
        self.label_146.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_146.setObjectName("label_146")
        self.mon_lch_kal = QtWidgets.QLabel(self.frame)
        self.mon_lch_kal.setGeometry(QtCore.QRect(760, 1540, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_kal.setFont(font)
        self.mon_lch_kal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_kal.setObjectName("mon_lch_kal")
        self.label_56 = QtWidgets.QLabel(self.frame)
        self.label_56.setGeometry(QtCore.QRect(830, 1540, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_56.setObjectName("label_56")
        self.label_60 = QtWidgets.QLabel(self.frame)
        self.label_60.setGeometry(QtCore.QRect(710, 1540, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_60.setObjectName("label_60")
        self.label_145 = QtWidgets.QLabel(self.frame)
        self.label_145.setGeometry(QtCore.QRect(570, 1470, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_145.setFont(font)
        self.label_145.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_145.setObjectName("label_145")
        self.mon_brf_g_5 = QtWidgets.QLabel(self.frame)
        self.mon_brf_g_5.setGeometry(QtCore.QRect(580, 1320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g_5.setFont(font)
        self.mon_brf_g_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g_5.setObjectName("mon_brf_g_5")
        self.label_63 = QtWidgets.QLabel(self.frame)
        self.label_63.setGeometry(QtCore.QRect(840, 1320, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_63.setObjectName("label_63")
        self.mon_lch_g_2 = QtWidgets.QLabel(self.frame)
        self.mon_lch_g_2.setGeometry(QtCore.QRect(670, 1320, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_g_2.setFont(font)
        self.mon_lch_g_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_g_2.setObjectName("mon_lch_g_2")
        self.label_64 = QtWidgets.QLabel(self.frame)
        self.label_64.setGeometry(QtCore.QRect(720, 1320, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_64.setObjectName("label_64")
        self.mon_lch_kal_2 = QtWidgets.QLabel(self.frame)
        self.mon_lch_kal_2.setGeometry(QtCore.QRect(770, 1320, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_kal_2.setFont(font)
        self.mon_lch_kal_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_kal_2.setObjectName("mon_lch_kal_2")
        self.label_148 = QtWidgets.QLabel(self.frame)
        self.label_148.setGeometry(QtCore.QRect(580, 1270, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_148.setFont(font)
        self.label_148.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_148.setObjectName("label_148")
        self.mon_brf_g_6 = QtWidgets.QLabel(self.frame)
        self.mon_brf_g_6.setGeometry(QtCore.QRect(570, 1770, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g_6.setFont(font)
        self.mon_brf_g_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g_6.setObjectName("mon_brf_g_6")
        self.label_65 = QtWidgets.QLabel(self.frame)
        self.label_65.setGeometry(QtCore.QRect(830, 1770, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_65.setObjectName("label_65")
        self.label_147 = QtWidgets.QLabel(self.frame)
        self.label_147.setGeometry(QtCore.QRect(570, 1730, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_147.setFont(font)
        self.label_147.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_147.setObjectName("label_147")
        self.mon_lch_g_3 = QtWidgets.QLabel(self.frame)
        self.mon_lch_g_3.setGeometry(QtCore.QRect(660, 1770, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_g_3.setFont(font)
        self.mon_lch_g_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_g_3.setObjectName("mon_lch_g_3")
        self.label_66 = QtWidgets.QLabel(self.frame)
        self.label_66.setGeometry(QtCore.QRect(710, 1770, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_66.setObjectName("label_66")
        self.mon_lch_kal_3 = QtWidgets.QLabel(self.frame)
        self.mon_lch_kal_3.setGeometry(QtCore.QRect(760, 1770, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_lch_kal_3.setFont(font)
        self.mon_lch_kal_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_lch_kal_3.setObjectName("mon_lch_kal_3")
        self.label_151 = QtWidgets.QLabel(self.frame)
        self.label_151.setGeometry(QtCore.QRect(570, 1700, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_151.setFont(font)
        self.label_151.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_151.setObjectName("label_151")
        self.mon_brf_g_7 = QtWidgets.QLabel(self.frame)
        self.mon_brf_g_7.setGeometry(QtCore.QRect(580, 2200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_brf_g_7.setFont(font)
        self.mon_brf_g_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_brf_g_7.setObjectName("mon_brf_g_7")
        self.label_152 = QtWidgets.QLabel(self.frame)
        self.label_152.setGeometry(QtCore.QRect(580, 2150, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_152.setFont(font)
        self.label_152.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_152.setObjectName("label_152")
        self.label_67 = QtWidgets.QLabel(self.frame)
        self.label_67.setGeometry(QtCore.QRect(720, 2200, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.frame)
        self.label_68.setGeometry(QtCore.QRect(820, 2200, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.label_68.setObjectName("label_68")
        self.mon_dnr_kal_2 = QtWidgets.QLabel(self.frame)
        self.mon_dnr_kal_2.setGeometry(QtCore.QRect(770, 2200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_dnr_kal_2.setFont(font)
        self.mon_dnr_kal_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_dnr_kal_2.setObjectName("mon_dnr_kal_2")
        self.mon_dnr_g_2 = QtWidgets.QLabel(self.frame)
        self.mon_dnr_g_2.setGeometry(QtCore.QRect(670, 2200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mon_dnr_g_2.setFont(font)
        self.mon_dnr_g_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;\n"
"")
        self.mon_dnr_g_2.setObjectName("mon_dnr_g_2")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(180, 1640, 251, 181))
        self.label_13.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("page2_images/109159.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(180, 1860, 251, 181))
        self.label_14.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("page2_images/p_O.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(180, 2080, 251, 181))
        self.label_15.setStyleSheet("border:10px solid rgb(34, 34, 46);\n"
"border-radius: 30;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("page2_images/0d9ad60260317ce10b06773a0ef8e9c5.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label.raise_()
        self.plainTextEdit.raise_()
        self.plainTextEdit_2.raise_()
        self.label_5.raise_()
        self.label_72.raise_()
        self.label_2.raise_()
        self.label_11.raise_()
        self.label_6.raise_()
        self.label_10.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_52.raise_()
        self.mon_brf_g.raise_()
        self.mon_brf_kal.raise_()
        self.label_51.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.label_47.raise_()
        self.label_50.raise_()
        self.label_55.raise_()
        self.label_144.raise_()
        self.mon_brf_g_2.raise_()
        self.label_73.raise_()
        self.label_57.raise_()
        self.label_8.raise_()
        self.label_58.raise_()
        self.label_9.raise_()
        self.label_59.raise_()
        self.label_12.raise_()
        self.mon_brf_g_4.raise_()
        self.label_149.raise_()
        self.label_61.raise_()
        self.mon_dnr_kal.raise_()
        self.label_150.raise_()
        self.mon_dnr_g.raise_()
        self.label_62.raise_()
        self.mon_brf_g_3.raise_()
        self.mon_lch_g.raise_()
        self.label_146.raise_()
        self.mon_lch_kal.raise_()
        self.label_56.raise_()
        self.label_60.raise_()
        self.label_145.raise_()
        self.mon_brf_g_5.raise_()
        self.label_63.raise_()
        self.mon_lch_g_2.raise_()
        self.label_64.raise_()
        self.mon_lch_kal_2.raise_()
        self.label_148.raise_()
        self.mon_brf_g_6.raise_()
        self.label_65.raise_()
        self.label_147.raise_()
        self.mon_lch_g_3.raise_()
        self.label_66.raise_()
        self.mon_lch_kal_3.raise_()
        self.label_151.raise_()
        self.mon_brf_g_7.raise_()
        self.label_152.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.mon_dnr_kal_2.raise_()
        self.mon_dnr_g_2.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Меню на каждый день"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "В данной записи представлено разнообразное меню на неделю с готовым отчетом по потребляемым калориям и питательным веществам. Это меню было составлено исходя из следующих принципов:\n"
""))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "• На завтрак мы едим лёгкую и быстро готовящуюся пищу, например, кашу\n"
"• На обед и завтрак приходится самый калорийный приём пищи\n"
"• На ужин мы готовим рецепт средней калорийности\n"
"• По крайней одно рыбное или мясное блюдо\n"
"• Средний дневной рацион потребления углеводов, жиров и белков должен удовлетворять рекомендованную норму \n"
"• В меню входит белковая, углеводная и овощная пища\n"
"• Для того, чтобы разнообразить рацион питания, мы один и тот же гарнир (рис, картофель или макароны), и стараемся избегать повторения одних и тех же продуктов."))
        self.label_5.setText(_translate("MainWindow", "Ужин"))
        self.label_72.setText(_translate("MainWindow", "Каждый день"))
        self.label_7.setText(_translate("MainWindow", "Геркулес на воде"))
        self.label_52.setText(_translate("MainWindow", "ккал"))
        self.mon_brf_g.setText(_translate("MainWindow", "500"))
        self.mon_brf_kal.setText(_translate("MainWindow", "380"))
        self.label_51.setText(_translate("MainWindow", "г  /"))
        self.label_47.setText(_translate("MainWindow", "Обед"))
        self.label_50.setText(_translate("MainWindow", "Перекус"))
        self.label_55.setText(_translate("MainWindow", "Завтрак"))
        self.label_144.setText(_translate("MainWindow", "Изюм, хлеб, кофе"))
        self.mon_brf_g_2.setText(_translate("MainWindow", "Всего:"))
        self.label_73.setText(_translate("MainWindow", "Приятного аппетита!"))
        self.label_57.setText(_translate("MainWindow", "Полдник"))
        self.label_58.setText(_translate("MainWindow", "Ужин"))
        self.label_59.setText(_translate("MainWindow", "Ночник"))
        self.mon_brf_g_4.setText(_translate("MainWindow", "Всего:"))
        self.label_149.setText(_translate("MainWindow", "Зеленый салат, чай"))
        self.label_61.setText(_translate("MainWindow", "ккал"))
        self.mon_dnr_kal.setText(_translate("MainWindow", "166"))
        self.label_150.setText(_translate("MainWindow", "Гречка с грибами"))
        self.mon_dnr_g.setText(_translate("MainWindow", "400"))
        self.label_62.setText(_translate("MainWindow", "г  /"))
        self.mon_brf_g_3.setText(_translate("MainWindow", "Всего:"))
        self.mon_lch_g.setText(_translate("MainWindow", "600"))
        self.label_146.setText(_translate("MainWindow", "Тефтели, салат, чай"))
        self.mon_lch_kal.setText(_translate("MainWindow", "345"))
        self.label_56.setText(_translate("MainWindow", "ккал"))
        self.label_60.setText(_translate("MainWindow", "г  /"))
        self.label_145.setText(_translate("MainWindow", "Куриная лапша"))
        self.mon_brf_g_5.setText(_translate("MainWindow", "Всего:"))
        self.label_63.setText(_translate("MainWindow", "ккал"))
        self.mon_lch_g_2.setText(_translate("MainWindow", "250"))
        self.label_64.setText(_translate("MainWindow", "г  /"))
        self.mon_lch_kal_2.setText(_translate("MainWindow", "133"))
        self.label_148.setText(_translate("MainWindow", "Кефир маложирный"))
        self.mon_brf_g_6.setText(_translate("MainWindow", "Всего:"))
        self.label_65.setText(_translate("MainWindow", "ккал"))
        self.label_147.setText(_translate("MainWindow", "Маложирный йогурт"))
        self.mon_lch_g_3.setText(_translate("MainWindow", "225"))
        self.label_66.setText(_translate("MainWindow", "г  /"))
        self.mon_lch_kal_3.setText(_translate("MainWindow", "135"))
        self.label_151.setText(_translate("MainWindow", "Яблоко"))
        self.mon_brf_g_7.setText(_translate("MainWindow", "Всего:"))
        self.label_152.setText(_translate("MainWindow", "Ряженка"))
        self.label_67.setText(_translate("MainWindow", "г  /"))
        self.label_68.setText(_translate("MainWindow", "ккал"))
        self.mon_dnr_kal_2.setText(_translate("MainWindow", "100"))
        self.mon_dnr_g_2.setText(_translate("MainWindow", "200"))
